### ISSUE TITLE
Can't see or load the S3 plugins in CTFd

### ISSUE THREAD

**Issue by davidlebr1** [CTFd/CTFd-S3-plugin#1]
Hi, 

is it normal that I can't see the S3 plugins inside the CTFd framework? 
Also, I tried to upload and it did'nt work. I got this error : global name 'app' is not defined. 

I follow exactly the instructions in the readme. 

Thanks!

**Comment by ColdHeat** [comment]
You won't be able to see it in the admin interface yet because it doesn't have a config.html page defined so it isn't listed as a configurable plugin.

Do you have a stack trace perhaps? 

CTFd has undergone some changes recently which may have changed the requirements of the plugin. If there is an issue give me some time and I'll update the plugin accordingly.

**Comment by davidlebr1** [comment]
Yes, this is the stack trace : 
```
127.0.0.1 - - [28/Mar/2017 19:05:45] "GET /files/5761ca6e6abf2869e1ffe62520d0d13e/IMG_20170326_122821.jpg HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\David\Documents\github\CTFd-bell\CTFd\plugins\s3\s3.py", line 31, in file_handler
    s3 = get_s3_conn()
  File "C:\Users\David\Documents\github\CTFd-bell\CTFd\plugins\s3\s3.py", line 19, in get_s3_conn
    if app.config.get('ACCESS_KEY_ID') and app.config.get('SECRET_ACCESS_KEY'):
NameError: global name 'app' is not defined
```

**Comment by ColdHeat** [comment]
@davidlebr1 This should be fixed now. Issues was that the location of the view handlers changed due to some CTFd refactoring. Thanks for bringing this to my attention.
